// ============================================================
//  AMGF - Sistema de Traduceri / Translation System
//  Limbi / Languages: RO / EN / FR / RU
// ============================================================

const translations = {

  ro: {
    "nav-about":"Despre","nav-why":"De ce AMGF?","nav-links":"Link-uri Utile",
    "nav-vision":"Viziune","nav-roadmap":"Roadmap","nav-liquidity":"Transparenta",
    "nav-tokenomics":"Tokenomics","nav-whitepaper":"Cartea Alba","nav-disclaimer":"Disclaimer",
    "hero-title":"AMGF","hero-subtitle":"Libertate Financiara",
    "about-title":"Cine Suntem si De Ce AMGF?",
    "about-p1":'Salut, sunt <b>"Fondatorul AMGF"</b>, o persoana obisnuita, cu o pasiune extraordinara pentru viitorul pe care il aduc Web3 si criptomonedele. La 53 de ani, am explorat acest univers digital de cativa ani, participand la numeroase proiecte si airdrop-uri. Am vazut atat povesti de succes incredibile, cat si esecuri dureroase - experiente care m-au invatat enorm despre potentialul si riscurile acestui domeniu.',
    "about-p2":"Ca multi altii, m-am saturat sa investesc timp si incredere in proiecte anonime, conduse de interese necunoscute. Asa s-a nascut AMGF. Am decis ca este timpul sa investesc in mine insumi si sa construiesc un proiect in care cred cu adevarat, bazat pe transparenta, utilitate si o comunitate autentica.",
    "about-p3":'AMGF nu este creat de un "expert financiar" de pe Wall Street, ci de o persoana reala, care intelege provocarile si aspiratiile celor care isi doresc libertatea financiara. Viziunea mea pentru AMGF este simpla: sa cream un ecosistem unde oricine, indiferent de varsta sau experienta anterioara, poate invata, contribui si creste alaturi de noi.',
    "about-p4":"Suntem aici pentru a construi pe termen lung, impreuna cu voi. Increderea se castiga prin fapte, nu prin vorbe, iar AMGF este angajamentul meu fata de un viitor mai bun, construit pas cu pas, alaturi de comunitate.",
    "why-title":"De ce AMGF?",
    "why-p1":"In peisajul dinamic si adesea haotic al Web3 si al criptomonedelor, promisiunile abunda, dar increderea si informatiile autentice sunt adesea greu de gasit. Multi, inclusiv eu, am simtit nevoia unui loc unde libertatea financiara sa fie nu doar un vis, ci o calatorie reala, sustinuta de cunoastere si o comunitate dedicata.",
    "why-p2":"Aici intervine AMGF. Suntem mai mult decat un token; suntem un ecosistem construit de o persoana obisnuita, la fel ca tine, pasionata de viitor si de potentialul decentralizat. Misiunea noastra este sa oferim un spatiu transparent si accesibil unde vei putea invata, contribui si creste alaturi de o comunitate unita, transformand aspiratia spre independenta financiara intr-o realitate concreta, pas cu pas.",
    "links-title":"Comunitate & Tranzactionare","links-desc":"Adresa de Contract (BASE):",
    "link-telegram":"Contact Telegram (@amgf_libertate_bot)","link-exchange1":"Cumpara pe Uniswap (Base)","link-exchange2":"Grafic DexScreener",
    "vision-title":"Viziune pe termen lung",
    "vision-p1":"Viziunea noastra pentru AMGF depaseste orizontul unui simplu token; ne propunem sa construim un ecosistem digital vibrant si autosustenabil, o adevarata Organizatie Autonoma Descentralizata (DAO), unde libertatea financiara devine accesibila tuturor. Pe termen lung, AMGF va fi recunoscut nu doar ca un simbol al potentialului Web3, ci ca un catalizator pentru transformarea personala si colectiva.",
    "vision-p2":"Ne imaginam un viitor in care detinatorii de AMGF sunt co-proprietari si arhitecti ai propriului lor destin financiar. Prin platforma noastra, ei vor avea acces la:",
    "vision-li1":"<b>O educatie financiara gamificata si practica</b>, adaptata nevoilor reale ale fiecaruia, recompensata direct prin sistemul nostru <b>Learn-to-Earn</b>.",
    "vision-li2":"<b>Instrumente intuitive si analize personalizate</b>, care demistifica lumea investitiilor si ii ajuta sa ia decizii informate, depasind zgomotul informational.",
    "vision-li3":"<b>O comunitate globala activa si interconectata</b>, unde membrii se sprijina reciproc si colaboreaza la dezvoltarea proiectului prin mecanismul <b>Build-to-Earn</b>.",
    "vision-li4":"<b>Un sistem de guvernanta DAO robust si transparent</b>, unde fiecare detinator de AMGF are o voce reala in deciziile cheie ale ecosistemului.",
    "vision-p3":"Pe masura ce ecosistemul AMGF se maturizeaza, ne vedem transformandu-ne intr-un model de autonomie comunitara si de sustenabilitate financiara, unde valoarea este generata si distribuita de si pentru membrii sai. AMGF va fi un exemplu al modului in care tehnologia blockchain poate imputernici indivizii sa-si preia controlul asupra viitorului lor financiar.",
    "eco-title":"Ecosistemul AMGF",
    "eco-badge":"✅ Toate aplicatiile sunt gratuite",
    "eco-intro":'Fondatorul AMGF construieste activ un ecosistem complet de aplicatii Web3, toate disponibile gratuit pentru comunitate. Pe viitor, o <strong>taxa simbolica</strong> poate fi introdusa pentru a sustine dezvoltarea continua a proiectului.',
    "eco-free":"✅ GRATUIT","eco-open":"Deschide ↗",
    "eco-card1-desc":"Portofel non-custodial pe reteaua Base. Tu detii cheile private - securitate maxima fara dependenta de terti.",
    "eco-card2-desc":"Gestioneaza si participa la campaniile de airdrop AMGF. Recompenseaza participarea activa in comunitate.",
    "eco-card3-desc":"Pune tokenurile AMGF la lucru si genereaza randamente pasive. Contribuie la stabilitatea ecosistemului.",
    "eco-card4-desc":"Platforma de dezvoltare si colaborare pentru membrii tehnici. Sustine mecanismul Build-to-Earn al comunitatii.",
    "eco-card5-desc":"Platforma educationala crypto si finante. Completeaza lectii, castiga puncte si primesti recompense in $AMGF trimestrial.",
    "eco-card6-desc":"Bot Telegram pentru interactiunea cu comunitatea, notificari in timp real si informatii despre tokenul AMGF.",
    "eco-more":"🌐 Vezi toate aplicatiile ↗",
    "eco-note":'💡 Toate aplicatiile sunt in prezent <strong>100% gratuite</strong>. Pe viitor, o taxa simbolica poate fi introdusa pentru a sustine dezvoltarea continua si echipa proiectului. Comunitatea va fi consultata inainte de orice schimbare.',
    "roadmap-title":"Roadmap","roadmap-phase1-label":"Faza 1 · 2024-2025 · Fundatie",
    "roadmap-phase1-title":"Lansare & Infrastructura",
    "roadmap-phase1-desc":"Crearea tokenului AMGF pe reteaua Base. Lansarea site-ului principal amgf-finance.com. Construirea comunitatii Telegram. Publicarea Cartii Albe v1.0. Lansarea AMGF Wallet N.C., Liberty Bot si Airdrop Manager.",
    "roadmap-phase2-label":"Faza 2 · 2025 · Crestere","roadmap-phase2-title":"Ecosistem & Comunitate",
    "roadmap-phase2-desc":"Lansarea Staking Hub si AMGF Code App. Campanii de airdrop strategice. Listare pe DEX-uri (Uniswap / Base). Lansarea Crypto Vault Keeper. Parteneriate strategice. Cresterea comunitatii la 10,000+ membri.",
    "roadmap-phase3-label":"Faza 3 · 2026 · Maturizare","roadmap-phase3-title":"DAO & Learn-to-Earn",
    "roadmap-phase3-desc":"Implementarea mecanismului DAO complet. Lansarea platformei educationale Learn-to-Earn. Sistem Build-to-Earn activ. Audit smart contract independent. Extinderea ecosistemului cu noi instrumente si integrari.",
    "roadmap-phase4-label":"Faza 4 · 2026-2027 · Expansiune","roadmap-phase4-title":"Autonomie & Scalare",
    "roadmap-phase4-desc":"Listare pe exchange-uri centralizate (CEX). Guvernanta DAO complet autonoma. Fond colectiv administrat de comunitate. Extindere internationala. AMGF ca model de autonomie comunitara in Web3.",
    "roadmap-status-done":"✔ Realizat","roadmap-status-active":"⚡ In desfasurare","roadmap-status-soon":"🔜 In pregatire","roadmap-status-future":"◎ Viitor",
    "liq-title":"Transparenta & Lichiditate Blocata",
    "liq-founder-msg":'🔒 <strong>Angajamentul Fondatorului:</strong> Fondatorul AMGF adauga lichiditate treptat si o blocheaza pe GemPad pentru perioade lungi de timp. Aceasta este dovada concreta a angajamentului pe termen lung fata de comunitate — fondurile nu pot fi retrase pana la expirarea perioadei de blocare. <strong>Transparenta nu este o promisiune, ci o realitate verificabila public.</strong>',
    "liq-card1-title":"Lichiditate Blocata","liq-card1-desc":'Uniswap V2 · Reteaua Base<br>Blocat pana pe <strong style="color:#E8B832;">5 Iunie 2027</strong>',
    "liq-card2-title":"Echipa & Fondator","liq-card2-desc":'Team & Founder Lock<br><strong style="color:#E8B832;">451+ zile</strong> ramase',
    "liq-card3-title":"Trezorerie DAO","liq-card3-desc":'DAO Treasury & Ecosystem<br><strong style="color:#E8B832;">Vesting treptat</strong> · 534+ zile',
    "liq-card4-title":"Rezerva Fondator","liq-card4-desc":'Founder Reserve Lock<br><strong style="color:#E8B832;">841+ zile</strong> ramase',
    "liq-locked":"🔒 BLOCAT","liq-vesting":"📈 VESTING",
    "liq-total-label":"Total Fonduri Blocate & Vesting","liq-total-sub":"Verificat pe GemPad · Reteaua Base · Actualizat in timp real","liq-verify-btn":"Verifica pe GemPad",
    "tokenomics-title":"Alocarea Tokenurilor AMGF (Actualizata)",
    "tokenomics-th1":"Categorie de Alocare","tokenomics-th2":"Procent (%)","tokenomics-th3":"Cantitate AMGF","tokenomics-th4":"Scop si Justificare","tokenomics-th5":"Plan de Vesting / Acces",
    "tokenomics-row1-cat":"Comunitate & Ecosistem","tokenomics-row1-scope":"Sustinerea cresterii organice prin recompense pentru participare (Learn-to-Earn, Build-to-Earn), campanii de promovare si airdrop-uri strategice.","tokenomics-row1-vesting":"Eliberare treptata pe parcursul a 5-10 ani.",
    "tokenomics-row2-cat":"Trezorerie DAO / Dezvoltare Ecosistem","tokenomics-row2-scope":"Finantarea dezvoltarii platformei, noi parteneriate si audituri sub guvernanta comunitatii.","tokenomics-row2-vesting":"Blocate intr-o trezorerie DAO.",
    "tokenomics-row3-cat":"Fond de Lichiditate Initiala (DEX)","tokenomics-row3-scope":"Asigurarea lichiditatii pe burse descentralizate (DEX) pe Base.","tokenomics-row3-vesting":"Blocata prin contracte de staking/farming pentru cel putin 2-5 ani.",
    "tokenomics-row4-cat":"Echipa si Fondator","tokenomics-row4-scope":"Alocare pentru Fondator si echipa de baza. (Fondatorul: 5%, Echipa 5%)","tokenomics-row4-vesting":"Cliff de 1 an, urmat de eliberare pe 3 ani.",
    "tokenomics-total":"Total","tokenomics-note":"<b>Nota:</b> Strategia Tokenomics este proiectata pentru a minimiza presiunea de vanzare.",
    "disclaimer-title":"Disclaimer Legal Important",
    "disclaimer-p1":"Informatiile prezentate pe acest site nu constituie sfaturi financiare, de investitii sau juridice. Investitiile in criptomonede si tokenuri digitale implica riscuri semnificative, inclusiv pierderea totala a capitalului investit. Preturile pot fi extrem de volatile si imprevizibile.",
    "disclaimer-p2":"Efectuati propria cercetare (DYOR - Do Your Own Research) inainte de orice decizie de investitie. Consultati un consilier financiar autorizat daca aveti dubii. Performantele trecute nu garanteaza rezultate viitoare.",
    "disclaimer-p3":"Participarea la ecosistemul AMGF implica acceptarea acestor termeni si conditii. AMGF nu este responsabil pentru pierderile financiare rezultate din utilizarea platformei sau din deciziile de investitie ale utilizatorilor.",
    "footer-copyright":"© 2025 AMGF Financial Freedom. Toate drepturile rezervate.",
    "footer-contact":"Contact: <a href='mailto:AMG3775@protonmail.com' style='color:#E8B832;'>AMG3775@protonmail.com</a>",
  },

  en: {
    "nav-about":"About","nav-why":"Why AMGF?","nav-links":"Useful Links",
    "nav-vision":"Vision","nav-roadmap":"Roadmap","nav-liquidity":"Transparency",
    "nav-tokenomics":"Tokenomics","nav-whitepaper":"White Paper","nav-disclaimer":"Disclaimer",
    "hero-title":"AMGF","hero-subtitle":"Financial Freedom",
    "about-title":"Who We Are and Why AMGF?",
    "about-p1":'Hello, I am the <b>"AMGF Founder"</b> — an ordinary person with an extraordinary passion for the future that Web3 and cryptocurrencies bring. At 53, I have explored this digital universe for several years, participating in numerous projects and airdrops. I have witnessed incredible success stories as well as painful failures — experiences that taught me enormously about the potential and risks of this space.',
    "about-p2":"Like many others, I grew tired of investing time and trust in anonymous projects driven by unknown interests. That is how AMGF was born. I decided it was time to invest in myself and build a project I truly believe in, based on transparency, utility, and an authentic community.",
    "about-p3":'AMGF was not created by a Wall Street "financial expert" but by a real person who understands the challenges and aspirations of those seeking financial freedom. My vision for AMGF is simple: to create an ecosystem where anyone, regardless of age or prior experience, can learn, contribute, and grow alongside us.',
    "about-p4":"We are here to build for the long term, together with you. Trust is earned through actions, not words, and AMGF is my commitment to a better future, built step by step, alongside the community.",
    "why-title":"Why AMGF?",
    "why-p1":"In the dynamic and often chaotic landscape of Web3 and cryptocurrencies, promises abound, but trust and authentic information are often hard to find. Many, including myself, have felt the need for a place where financial freedom is not just a dream but a real journey, supported by knowledge and a dedicated community.",
    "why-p2":"This is where AMGF comes in. We are more than a token; we are an ecosystem built by an ordinary person, just like you, passionate about the future and decentralized potential. Our mission is to provide a transparent and accessible space where you can learn, contribute, and grow alongside a united community, turning the aspiration for financial independence into concrete reality, step by step.",
    "links-title":"Community & Trading","links-desc":"Contract Address (BASE):",
    "link-telegram":"Telegram Contact (@amgf_libertate_bot)","link-exchange1":"Buy on Uniswap (Base)","link-exchange2":"DexScreener Chart",
    "vision-title":"Long-term Vision",
    "vision-p1":"Our vision for AMGF goes beyond a simple token; we aim to build a vibrant and self-sustaining digital ecosystem, a true Decentralized Autonomous Organization (DAO), where financial freedom becomes accessible to everyone. In the long run, AMGF will be recognized not only as a symbol of Web3's potential but as a catalyst for personal and collective transformation.",
    "vision-p2":"We envision a future where AMGF holders are co-owners and architects of their own financial destiny. Through our platform, they will have access to:",
    "vision-li1":"<b>Gamified and practical financial education</b>, tailored to everyone's real needs, rewarded directly through our <b>Learn-to-Earn</b> system.",
    "vision-li2":"<b>Intuitive tools and personalized analytics</b>, demystifying the investment world and helping members make informed decisions.",
    "vision-li3":"<b>An active and interconnected global community</b>, where members support each other and collaborate on project development through the <b>Build-to-Earn</b> mechanism.",
    "vision-li4":"<b>A robust and transparent DAO governance system</b>, where every AMGF holder has a real voice in the ecosystem's key decisions.",
    "vision-p3":"As the AMGF ecosystem matures, we see ourselves becoming a model of community autonomy and financial sustainability, where value is generated and distributed by and for its members. AMGF will be an example of how blockchain technology can empower individuals to take control of their financial future.",
    "eco-title":"The AMGF Ecosystem",
    "eco-badge":"✅ All applications are free",
    "eco-intro":'The AMGF Founder is actively building a complete ecosystem of Web3 applications, all available for free to the community. In the future, a <strong>symbolic fee</strong> may be introduced to support the continuous development of the project.',
    "eco-free":"✅ FREE","eco-open":"Open ↗",
    "eco-card1-desc":"Non-custodial wallet on the Base network. You hold the private keys — maximum security without third-party dependency.",
    "eco-card2-desc":"Manage and participate in AMGF airdrop campaigns. Rewards active participation in the community.",
    "eco-card3-desc":"Put your AMGF tokens to work and generate passive returns. Contributes to the stability of the ecosystem.",
    "eco-card4-desc":"Development and collaboration platform for technical members. Supports the community's Build-to-Earn mechanism.",
    "eco-card5-desc":"Crypto and finance educational platform. Complete lessons, earn points and receive $AMGF rewards quarterly.",
    "eco-card6-desc":"Telegram bot for community interaction, real-time notifications and information about the AMGF token.",
    "eco-more":"🌐 View all applications ↗",
    "eco-note":'💡 All applications are currently <strong>100% free</strong>. In the future, a symbolic fee may be introduced to support continuous development. The community will be consulted before any change.',
    "roadmap-title":"Roadmap","roadmap-phase1-label":"Phase 1 · 2024-2025 · Foundation",
    "roadmap-phase1-title":"Launch & Infrastructure",
    "roadmap-phase1-desc":"Creation of the AMGF token on the Base network. Launch of the main website amgf-finance.com. Building the Telegram community. Publishing the White Paper v1.0. Launch of AMGF Wallet N.C., Liberty Bot and Airdrop Manager.",
    "roadmap-phase2-label":"Phase 2 · 2025 · Growth","roadmap-phase2-title":"Ecosystem & Community",
    "roadmap-phase2-desc":"Launch of Staking Hub and AMGF Code App. Strategic airdrop campaigns. Listing on DEXs (Uniswap / Base). Launch of Crypto Vault Keeper. Strategic partnerships. Growing the community to 10,000+ members.",
    "roadmap-phase3-label":"Phase 3 · 2026 · Maturity","roadmap-phase3-title":"DAO & Learn-to-Earn",
    "roadmap-phase3-desc":"Full DAO mechanism implementation. Launch of the Learn-to-Earn educational platform. Active Build-to-Earn system. Independent smart contract audit. Ecosystem expansion with new tools and integrations.",
    "roadmap-phase4-label":"Phase 4 · 2026-2027 · Expansion","roadmap-phase4-title":"Autonomy & Scaling",
    "roadmap-phase4-desc":"Listing on centralized exchanges (CEX). Fully autonomous DAO governance. Community-managed collective fund. International expansion. AMGF as a model of community autonomy in Web3.",
    "roadmap-status-done":"✔ Completed","roadmap-status-active":"⚡ In Progress","roadmap-status-soon":"🔜 Coming Soon","roadmap-status-future":"◎ Future",
    "liq-title":"Transparency & Locked Liquidity",
    "liq-founder-msg":'🔒 <strong>Founder\'s Commitment:</strong> The AMGF Founder gradually adds liquidity and locks it on GemPad for long periods. This is concrete proof of long-term commitment to the community — funds cannot be withdrawn until the lock period expires. <strong>Transparency is not a promise, but a publicly verifiable reality.</strong>',
    "liq-card1-title":"Locked Liquidity","liq-card1-desc":'Uniswap V2 · Base Network<br>Locked until <strong style="color:#E8B832;">June 5, 2027</strong>',
    "liq-card2-title":"Team & Founder","liq-card2-desc":'Team & Founder Lock<br><strong style="color:#E8B832;">451+ days</strong> remaining',
    "liq-card3-title":"DAO Treasury","liq-card3-desc":'DAO Treasury & Ecosystem<br><strong style="color:#E8B832;">Gradual Vesting</strong> · 534+ days',
    "liq-card4-title":"Founder Reserve","liq-card4-desc":'Founder Reserve Lock<br><strong style="color:#E8B832;">841+ days</strong> remaining',
    "liq-locked":"🔒 LOCKED","liq-vesting":"📈 VESTING",
    "liq-total-label":"Total Locked Funds & Vesting","liq-total-sub":"Verified on GemPad · Base Network · Updated in real time","liq-verify-btn":"Verify on GemPad",
    "tokenomics-title":"AMGF Token Allocation (Updated)",
    "tokenomics-th1":"Allocation Category","tokenomics-th2":"Percentage (%)","tokenomics-th3":"AMGF Amount","tokenomics-th4":"Purpose & Justification","tokenomics-th5":"Vesting / Access Plan",
    "tokenomics-row1-cat":"Community & Ecosystem","tokenomics-row1-scope":"Supporting organic growth through participation rewards (Learn-to-Earn, Build-to-Earn), promotional campaigns and strategic airdrops.","tokenomics-row1-vesting":"Gradual release over 5-10 years.",
    "tokenomics-row2-cat":"DAO Treasury / Ecosystem Development","tokenomics-row2-scope":"Funding platform development, new partnerships and audits under community governance.","tokenomics-row2-vesting":"Locked in a DAO treasury.",
    "tokenomics-row3-cat":"Initial Liquidity Fund (DEX)","tokenomics-row3-scope":"Ensuring liquidity on decentralized exchanges (DEX) on Base.","tokenomics-row3-vesting":"Locked through staking/farming contracts for at least 2-5 years.",
    "tokenomics-row4-cat":"Team and Founder","tokenomics-row4-scope":"Allocation for Founder and core team. (Founder: 5%, Team: 5%)","tokenomics-row4-vesting":"1-year cliff, followed by 3-year release.",
    "tokenomics-total":"Total","tokenomics-note":"<b>Note:</b> The Tokenomics strategy is designed to minimize selling pressure.",
    "disclaimer-title":"Important Legal Disclaimer",
    "disclaimer-p1":"The information presented on this website does not constitute financial, investment or legal advice. Investments in cryptocurrencies and digital tokens involve significant risks, including total loss of invested capital. Prices can be extremely volatile and unpredictable.",
    "disclaimer-p2":"Conduct your own research (DYOR - Do Your Own Research) before any investment decision. Consult an authorized financial advisor if in doubt. Past performance does not guarantee future results.",
    "disclaimer-p3":"Participation in the AMGF ecosystem implies acceptance of these terms and conditions. AMGF is not responsible for financial losses resulting from the use of the platform or from users' investment decisions.",
    "footer-copyright":"© 2025 AMGF Financial Freedom. All rights reserved.",
    "footer-contact":"Contact: <a href='mailto:AMG3775@protonmail.com' style='color:#E8B832;'>AMG3775@protonmail.com</a>",
  },

  fr: {
    "nav-about":"À propos","nav-why":"Pourquoi AMGF?","nav-links":"Liens Utiles",
    "nav-vision":"Vision","nav-roadmap":"Feuille de Route","nav-liquidity":"Transparence",
    "nav-tokenomics":"Tokenomics","nav-whitepaper":"Livre Blanc","nav-disclaimer":"Avertissement",
    "hero-title":"AMGF","hero-subtitle":"Liberté Financière",
    "about-title":"Qui Sommes-Nous et Pourquoi AMGF?",
    "about-p1":'Bonjour, je suis le <b>"Fondateur d\'AMGF"</b> — une personne ordinaire avec une passion extraordinaire pour l\'avenir qu\'apportent le Web3 et les cryptomonnaies. À 53 ans, j\'explore cet univers numérique depuis plusieurs années, participant à de nombreux projets et airdrops. J\'ai été témoin de succès incroyables ainsi que d\'échecs douloureux — des expériences qui m\'ont énormément appris.',
    "about-p2":"Comme beaucoup d'autres, j'en ai eu assez d'investir du temps et de la confiance dans des projets anonymes. C'est ainsi qu'est né AMGF. J'ai décidé d'investir en moi-même et de construire un projet en lequel je crois vraiment, basé sur la transparence et une communauté authentique.",
    "about-p3":"AMGF n'a pas été créé par un expert de Wall Street, mais par une vraie personne qui comprend les défis de ceux qui recherchent la liberté financière. Ma vision : créer un écosystème où chacun peut apprendre, contribuer et grandir avec nous.",
    "about-p4":"Nous sommes ici pour construire sur le long terme, ensemble. La confiance se gagne par les actes, et AMGF est mon engagement envers un avenir meilleur, construit pas à pas avec la communauté.",
    "why-title":"Pourquoi AMGF?",
    "why-p1":"Dans le paysage du Web3, les promesses abondent, mais la confiance est difficile à trouver. Beaucoup ont ressenti le besoin d'un endroit où la liberté financière est un vrai voyage, soutenu par la connaissance et une communauté dédiée.",
    "why-p2":"C'est là qu'intervient AMGF. Nous sommes plus qu'un token ; nous sommes un écosystème construit par une personne ordinaire. Notre mission : un espace transparent où vous pourrez apprendre, contribuer et grandir aux côtés d'une communauté unie.",
    "links-title":"Communauté & Trading","links-desc":"Adresse du Contrat (BASE):",
    "link-telegram":"Contact Telegram (@amgf_libertate_bot)","link-exchange1":"Acheter sur Uniswap (Base)","link-exchange2":"Graphique DexScreener",
    "vision-title":"Vision à Long Terme",
    "vision-p1":"Notre vision pour AMGF dépasse un simple token ; nous visons à construire un écosystème numérique vibrant, une véritable Organisation Autonome Décentralisée (DAO), où la liberté financière devient accessible à tous.",
    "vision-p2":"Nous imaginons un avenir où les détenteurs d'AMGF sont copropriétaires de leur destin financier. Via notre plateforme, ils auront accès à :",
    "vision-li1":"<b>Une éducation financière ludique et pratique</b>, récompensée par notre système <b>Learn-to-Earn</b>.",
    "vision-li2":"<b>Des outils intuitifs et des analyses personnalisées</b>, aidant les membres à prendre des décisions éclairées.",
    "vision-li3":"<b>Une communauté mondiale active</b>, où les membres collaborent via le mécanisme <b>Build-to-Earn</b>.",
    "vision-li4":"<b>Un système de gouvernance DAO transparent</b>, où chaque détenteur d'AMGF a une voix réelle.",
    "vision-p3":"À mesure que l'écosystème AMGF mûrit, nous deviendrons un modèle d'autonomie communautaire et de durabilité financière.",
    "eco-title":"L'Écosystème AMGF",
    "eco-badge":"✅ Toutes les applications sont gratuites",
    "eco-intro":'Le Fondateur d\'AMGF construit activement un écosystème complet d\'applications Web3, toutes disponibles gratuitement. À l\'avenir, une <strong>taxe symbolique</strong> pourra être introduite pour soutenir le développement continu du projet.',
    "eco-free":"✅ GRATUIT","eco-open":"Ouvrir ↗",
    "eco-card1-desc":"Portefeuille non-custodial sur le réseau Base. Vous détenez les clés privées — sécurité maximale sans dépendance tierce.",
    "eco-card2-desc":"Gérez et participez aux campagnes d'airdrop AMGF. Récompense la participation active dans la communauté.",
    "eco-card3-desc":"Mettez vos tokens AMGF au travail et générez des rendements passifs. Contribue à la stabilité de l'écosystème.",
    "eco-card4-desc":"Plateforme de développement et de collaboration pour les membres techniques. Soutient le mécanisme Build-to-Earn.",
    "eco-card5-desc":"Plateforme éducative crypto et finances. Complétez des leçons, gagnez des points et recevez des récompenses en $AMGF trimestriellement.",
    "eco-card6-desc":"Bot Telegram pour l'interaction communautaire, notifications en temps réel et informations sur le token AMGF.",
    "eco-more":"🌐 Voir toutes les applications ↗",
    "eco-note":'💡 Toutes les applications sont actuellement <strong>100% gratuites</strong>. À l\'avenir, une taxe symbolique pourra être introduite. La communauté sera consultée avant tout changement.',
    "roadmap-title":"Feuille de Route","roadmap-phase1-label":"Phase 1 · 2024-2025 · Fondation",
    "roadmap-phase1-title":"Lancement & Infrastructure",
    "roadmap-phase1-desc":"Création du token AMGF sur le réseau Base. Lancement du site amgf-finance.com. Construction de la communauté Telegram. Publication du Livre Blanc v1.0. Lancement d'AMGF Wallet N.C., Liberty Bot et Airdrop Manager.",
    "roadmap-phase2-label":"Phase 2 · 2025 · Croissance","roadmap-phase2-title":"Écosystème & Communauté",
    "roadmap-phase2-desc":"Lancement du Staking Hub et d'AMGF Code App. Campagnes d'airdrop stratégiques. Cotation sur les DEX. Lancement de Crypto Vault Keeper. Partenariats stratégiques. Croissance à 10 000+ membres.",
    "roadmap-phase3-label":"Phase 3 · 2026 · Maturité","roadmap-phase3-title":"DAO & Learn-to-Earn",
    "roadmap-phase3-desc":"Mise en place complète du DAO. Lancement de la plateforme Learn-to-Earn. Système Build-to-Earn actif. Audit indépendant du smart contract. Expansion de l'écosystème.",
    "roadmap-phase4-label":"Phase 4 · 2026-2027 · Expansion","roadmap-phase4-title":"Autonomie & Mise à l'Échelle",
    "roadmap-phase4-desc":"Cotation sur les CEX. Gouvernance DAO entièrement autonome. Fonds collectif géré par la communauté. Expansion internationale. AMGF comme modèle d'autonomie dans le Web3.",
    "roadmap-status-done":"✔ Réalisé","roadmap-status-active":"⚡ En cours","roadmap-status-soon":"🔜 En préparation","roadmap-status-future":"◎ Futur",
    "liq-title":"Transparence & Liquidité Bloquée",
    "liq-founder-msg":'🔒 <strong>Engagement du Fondateur :</strong> Le Fondateur d\'AMGF ajoute progressivement de la liquidité et la bloque sur GemPad pour de longues périodes. <strong>La transparence est une réalité vérifiable publiquement.</strong>',
    "liq-card1-title":"Liquidité Bloquée","liq-card1-desc":'Uniswap V2 · Réseau Base<br>Bloqué jusqu\'au <strong style="color:#E8B832;">5 Juin 2027</strong>',
    "liq-card2-title":"Équipe & Fondateur","liq-card2-desc":'Team & Founder Lock<br><strong style="color:#E8B832;">451+ jours</strong> restants',
    "liq-card3-title":"Trésorerie DAO","liq-card3-desc":'DAO Treasury & Ecosystem<br><strong style="color:#E8B832;">Vesting Progressif</strong> · 534+ jours',
    "liq-card4-title":"Réserve Fondateur","liq-card4-desc":'Founder Reserve Lock<br><strong style="color:#E8B832;">841+ jours</strong> restants',
    "liq-locked":"🔒 BLOQUÉ","liq-vesting":"📈 VESTING",
    "liq-total-label":"Total Fonds Bloqués & Vesting","liq-total-sub":"Vérifié sur GemPad · Réseau Base · Mis à jour en temps réel","liq-verify-btn":"Vérifier sur GemPad",
    "tokenomics-title":"Allocation des Tokens AMGF (Mise à jour)",
    "tokenomics-th1":"Catégorie d'Allocation","tokenomics-th2":"Pourcentage (%)","tokenomics-th3":"Quantité AMGF","tokenomics-th4":"Objectif & Justification","tokenomics-th5":"Plan de Vesting / Accès",
    "tokenomics-row1-cat":"Communauté & Écosystème","tokenomics-row1-scope":"Soutenir la croissance organique via des récompenses de participation et des airdrops stratégiques.","tokenomics-row1-vesting":"Libération progressive sur 5 à 10 ans.",
    "tokenomics-row2-cat":"Trésorerie DAO / Développement","tokenomics-row2-scope":"Financement du développement, nouveaux partenariats et audits sous gouvernance communautaire.","tokenomics-row2-vesting":"Bloqués dans une trésorerie DAO.",
    "tokenomics-row3-cat":"Fonds de Liquidité Initial (DEX)","tokenomics-row3-scope":"Assurer la liquidité sur les DEX sur Base.","tokenomics-row3-vesting":"Bloquée via des contrats de staking/farming pour au moins 2 à 5 ans.",
    "tokenomics-row4-cat":"Équipe et Fondateur","tokenomics-row4-scope":"Allocation pour le Fondateur et l'équipe principale. (Fondateur : 5%, Équipe : 5%)","tokenomics-row4-vesting":"Cliff d'1 an, suivi d'une libération sur 3 ans.",
    "tokenomics-total":"Total","tokenomics-note":"<b>Note :</b> La stratégie Tokenomics est conçue pour minimiser la pression de vente.",
    "disclaimer-title":"Avertissement Légal Important",
    "disclaimer-p1":"Les informations sur ce site ne constituent pas des conseils financiers. Les investissements en cryptomonnaies comportent des risques significatifs, y compris la perte totale du capital.",
    "disclaimer-p2":"Effectuez vos propres recherches (DYOR) avant toute décision. Consultez un conseiller financier agréé en cas de doute.",
    "disclaimer-p3":"La participation à l'écosystème AMGF implique l'acceptation de ces termes. AMGF n'est pas responsable des pertes financières des utilisateurs.",
    "footer-copyright":"© 2025 AMGF Financial Freedom. Tous droits réservés.",
    "footer-contact":"Contact : <a href='mailto:AMG3775@protonmail.com' style='color:#E8B832;'>AMG3775@protonmail.com</a>",
  },

  ru: {
    "nav-about":"О нас","nav-why":"Почему AMGF?","nav-links":"Полезные ссылки",
    "nav-vision":"Видение","nav-roadmap":"Дорожная карта","nav-liquidity":"Прозрачность",
    "nav-tokenomics":"Токеномика","nav-whitepaper":"Белая книга","nav-disclaimer":"Отказ от ответственности",
    "hero-title":"AMGF","hero-subtitle":"Финансовая свобода",
    "about-title":"Кто мы и почему AMGF?",
    "about-p1":'Привет, я <b>«Основатель AMGF»</b> — обычный человек с необыкновенной страстью к будущему, которое несут Web3 и криптовалюты. В 53 года я исследую этот цифровой мир уже несколько лет, участвуя в многочисленных проектах и аирдропах.',
    "about-p2":"Как и многие другие, я устал вкладывать время в анонимные проекты. Так родился AMGF — проект, основанный на прозрачности и подлинном сообществе.",
    "about-p3":"AMGF создан реальным человеком, понимающим стремления тех, кто ищет финансовую свободу. Моя цель: экосистема, где каждый может учиться и расти вместе с нами.",
    "about-p4":"Мы здесь для долгосрочного строительства вместе с вами. Доверие завоёвывается делами, и AMGF — моё обязательство перед лучшим будущим.",
    "why-title":"Почему AMGF?",
    "why-p1":"В мире Web3 обещаний много, но доверие найти сложно. Многие чувствовали необходимость в месте, где финансовая свобода — реальное путешествие, поддержанное знаниями.",
    "why-p2":"Здесь приходит AMGF. Мы больше, чем токен — экосистема, созданная обычным человеком. Наша миссия: прозрачное пространство, где вы учитесь и растёте вместе с сообществом.",
    "links-title":"Сообщество и торговля","links-desc":"Адрес контракта (BASE):",
    "link-telegram":"Контакт Telegram (@amgf_libertate_bot)","link-exchange1":"Купить на Uniswap (Base)","link-exchange2":"График DexScreener",
    "vision-title":"Долгосрочное видение",
    "vision-p1":"Наше видение AMGF — построить яркую DAO-экосистему, где финансовая свобода доступна каждому.",
    "vision-p2":"Мы представляем будущее, где держатели AMGF — совладельцы своей финансовой судьбы. Через платформу у них будет доступ к:",
    "vision-li1":"<b>Геймифицированному финансовому образованию</b> с вознаграждением через <b>Learn-to-Earn</b>.",
    "vision-li2":"<b>Интуитивным инструментам и аналитике</b>, помогающим принимать взвешенные решения.",
    "vision-li3":"<b>Активному глобальному сообществу</b>, сотрудничающему через <b>Build-to-Earn</b>.",
    "vision-li4":"<b>Надёжной системе управления DAO</b>, где каждый держатель имеет реальный голос.",
    "vision-p3":"По мере созревания экосистемы AMGF станет моделью общественной автономии и финансовой устойчивости.",
    "eco-title":"Экосистема AMGF",
    "eco-badge":"✅ Все приложения бесплатны",
    "eco-intro":'Основатель AMGF активно строит полную экосистему Web3-приложений, все доступны бесплатно для сообщества. В будущем может быть введена <strong>символическая плата</strong> для поддержки развития проекта.',
    "eco-free":"✅ БЕСПЛАТНО","eco-open":"Открыть ↗",
    "eco-card1-desc":"Некастодиальный кошелёк в сети Base. Вы владеете приватными ключами — максимальная безопасность без зависимости от третьих лиц.",
    "eco-card2-desc":"Управляйте и участвуйте в аирдроп-кампаниях AMGF. Награждает активное участие в сообществе.",
    "eco-card3-desc":"Заставьте токены AMGF работать и получайте пассивный доход. Способствует стабильности экосистемы.",
    "eco-card4-desc":"Платформа разработки и сотрудничества для технических членов. Поддерживает механизм Build-to-Earn.",
    "eco-card5-desc":"Образовательная платформа по крипто и финансам. Завершайте уроки, зарабатывайте очки и получайте вознаграждения в $AMGF ежеквартально.",
    "eco-card6-desc":"Telegram-бот для взаимодействия с сообществом, уведомлений в реальном времени и информации о токене AMGF.",
    "eco-more":"🌐 Посмотреть все приложения ↗",
    "eco-note":'💡 Все приложения сейчас <strong>100% бесплатны</strong>. В будущем может быть введена символическая плата. Сообщество будет проконсультировано перед любым изменением.',
    "roadmap-title":"Дорожная карта","roadmap-phase1-label":"Фаза 1 · 2024-2025 · Основание",
    "roadmap-phase1-title":"Запуск и инфраструктура",
    "roadmap-phase1-desc":"Создание токена AMGF в сети Base. Запуск сайта amgf-finance.com. Создание сообщества Telegram. Публикация Белой книги v1.0. Запуск AMGF Wallet N.C., Liberty Bot и Airdrop Manager.",
    "roadmap-phase2-label":"Фаза 2 · 2025 · Рост","roadmap-phase2-title":"Экосистема и сообщество",
    "roadmap-phase2-desc":"Запуск Staking Hub и AMGF Code App. Аирдроп-кампании. Листинг на DEX (Uniswap / Base). Запуск Crypto Vault Keeper. Стратегические партнёрства. Рост до 10 000+ участников.",
    "roadmap-phase3-label":"Фаза 3 · 2026 · Зрелость","roadmap-phase3-title":"DAO и Learn-to-Earn",
    "roadmap-phase3-desc":"Полная реализация DAO. Запуск платформы Learn-to-Earn. Активная система Build-to-Earn. Независимый аудит смарт-контракта. Расширение экосистемы.",
    "roadmap-phase4-label":"Фаза 4 · 2026-2027 · Расширение","roadmap-phase4-title":"Автономия и масштабирование",
    "roadmap-phase4-desc":"Листинг на CEX. Полностью автономное управление DAO. Коллективный фонд под управлением сообщества. Международное расширение. AMGF как модель автономии в Web3.",
    "roadmap-status-done":"✔ Выполнено","roadmap-status-active":"⚡ В процессе","roadmap-status-soon":"🔜 Скоро","roadmap-status-future":"◎ Будущее",
    "liq-title":"Прозрачность и заблокированная ликвидность",
    "liq-founder-msg":'🔒 <strong>Обязательство основателя:</strong> Основатель AMGF постепенно добавляет ликвидность и блокирует её на GemPad. <strong>Прозрачность — публично проверяемая реальность.</strong>',
    "liq-card1-title":"Заблокированная ликвидность","liq-card1-desc":'Uniswap V2 · Сеть Base<br>Заблокировано до <strong style="color:#E8B832;">5 июня 2027</strong>',
    "liq-card2-title":"Команда и основатель","liq-card2-desc":'Team & Founder Lock<br><strong style="color:#E8B832;">451+ дней</strong> осталось',
    "liq-card3-title":"Казначейство DAO","liq-card3-desc":'DAO Treasury & Ecosystem<br><strong style="color:#E8B832;">Постепенный вестинг</strong> · 534+ дней',
    "liq-card4-title":"Резерв основателя","liq-card4-desc":'Founder Reserve Lock<br><strong style="color:#E8B832;">841+ дней</strong> осталось',
    "liq-locked":"🔒 ЗАБЛОКИРОВАНО","liq-vesting":"📈 ВЕСТИНГ",
    "liq-total-label":"Всего заблокированных средств и вестинга","liq-total-sub":"Проверено на GemPad · Сеть Base · Обновляется в реальном времени","liq-verify-btn":"Проверить на GemPad",
    "tokenomics-title":"Распределение токенов AMGF (обновлено)",
    "tokenomics-th1":"Категория распределения","tokenomics-th2":"Процент (%)","tokenomics-th3":"Количество AMGF","tokenomics-th4":"Цель и обоснование","tokenomics-th5":"План вестинга / Доступ",
    "tokenomics-row1-cat":"Сообщество и экосистема","tokenomics-row1-scope":"Поддержка роста через вознаграждения (Learn-to-Earn, Build-to-Earn) и стратегические аирдропы.","tokenomics-row1-vesting":"Постепенное высвобождение в течение 5-10 лет.",
    "tokenomics-row2-cat":"Казначейство DAO / Развитие","tokenomics-row2-scope":"Финансирование разработки, партнёрств и аудитов под управлением сообщества.","tokenomics-row2-vesting":"Заблокированы в казначействе DAO.",
    "tokenomics-row3-cat":"Начальный фонд ликвидности (DEX)","tokenomics-row3-scope":"Обеспечение ликвидности на DEX в сети Base.","tokenomics-row3-vesting":"Заблокировано через контракты стейкинга/фарминга на срок не менее 2-5 лет.",
    "tokenomics-row4-cat":"Команда и основатель","tokenomics-row4-scope":"Распределение для основателя и основной команды. (Основатель: 5%, Команда: 5%)","tokenomics-row4-vesting":"Клифф 1 год, затем высвобождение в течение 3 лет.",
    "tokenomics-total":"Итого","tokenomics-note":"<b>Примечание:</b> Стратегия токеномики разработана для минимизации давления продаж.",
    "disclaimer-title":"Важный правовой отказ от ответственности",
    "disclaimer-p1":"Информация на сайте не является финансовым советом. Инвестиции в криптовалюты связаны со значительными рисками, включая полную потерю капитала.",
    "disclaimer-p2":"Проводите собственное исследование (DYOR) перед любым решением. При сомнениях проконсультируйтесь с финансовым советником.",
    "disclaimer-p3":"Участие в экосистеме AMGF подразумевает принятие этих условий. AMGF не несёт ответственности за финансовые потери пользователей.",
    "footer-copyright":"© 2025 AMGF Financial Freedom. Все права защищены.",
    "footer-contact":"Контакт: <a href='mailto:AMG3775@protonmail.com' style='color:#E8B832;'>AMG3775@protonmail.com</a>",
  }
};

// ============================================================
const langs      = ['ro', 'en', 'fr', 'ru'];
const langLabels = { ro: 'RO', en: 'EN', fr: 'FR', ru: 'RU' };
let currentLangIndex = 0;

function applyTranslations(lang) {
  const t = translations[lang];
  if (!t) return;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) el.innerHTML = t[key];
  });
  document.documentElement.lang = lang;
}

function updateToggleButton(lang) {
  const btn = document.getElementById('language-toggle');
  if (!btn) return;
  btn.textContent = langs.map(l => l === lang ? `[${langLabels[l]}]` : langLabels[l]).join(' / ');
}

function initLanguage() {
  const saved = localStorage.getItem('amgf-lang');
  if (saved && langs.includes(saved)) {
    currentLangIndex = langs.indexOf(saved);
  } else {
    const browserLang = (navigator.language || 'ro').slice(0, 2).toLowerCase();
    if (langs.includes(browserLang)) currentLangIndex = langs.indexOf(browserLang);
  }
  applyTranslations(langs[currentLangIndex]);
  updateToggleButton(langs[currentLangIndex]);
}

document.addEventListener('DOMContentLoaded', () => {
  const btn = document.getElementById('language-toggle');
  if (btn) {
    btn.addEventListener('click', () => {
      currentLangIndex = (currentLangIndex + 1) % langs.length;
      const newLang = langs[currentLangIndex];
      applyTranslations(newLang);
      updateToggleButton(newLang);
      localStorage.setItem('amgf-lang', newLang);
    });
  }
  initLanguage();
});
